export const CHART_LANG = 
{
  contextButtonTitle: 'Menú de contexto del gráfico',
  decimalPoint: ',',
  drillUpText: "Regresar a {series.name}",
  loading: 'Cargando...',
  months: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
  noData: 'No hay dato para mostrar',
  numericSymbolMagnitude: 1000,
  numericSymbols: ['Mil', 'Millones', 'G', 'T', 'P', 'E'],
  printChart: 'Imprimir gráfico',
  downloadPNG: 'Descargar imagen PNG ',
  downloadPDF: 'Descargar documento PDF',
  downloadSVG: 'Descargar imagen de tipo SVG ',
  downloadCSV: 'Descargar CSV',
  downloadXLS: 'Descargar XLS',
  viewFullscreen: 'Ver en pantalla completa',
  shortMonths: [
    'Ene',
    'Feb',
    'Mar',
    'Abr',
    'May',
    'Jun',
    'Jul',
    'Ago',
    'Sep',
    'Oct',
    'Nov',
    'Dic',
  ],
  thousandsSep: '',// '\u0020',
  viewData: 'Ver tabla de datos',
  weekdays: [
    'Domingo',
    'Lunes',
    'Martes',
    'Miércoles',
    'Jueves',
    'Viernes',
    'Sábado',
  ],

  accessibility: {
    announceNewData:{
      // announcementFormatter: onAnnounce,
      enabled: true,
      interruptUser: false,
      // minAnnounceInterval: 0
    },
    axis: {
      xAxisDescriptionPlural: 'El gráfico tiene {numAxes} ejes X, mostrando {#each names}{#unless @first},{/unless}{#if @last} y{/if} {this}{/each}.',
      xAxisDescriptionSingular: 'El gráfico tiene 1 eje X, mostrando {names[0]}. {ranges[0]}.',
      yAxisDescriptionPlural: 'El gráfico tiene {numAxes}  ejes Ye, mostrando {#each names}{#unless @first},{/unless}{#if @last} y{/if} {this}{/each}.',
      yAxisDescriptionSingular: 'El gráfico tiene 1 eje Ye, mostrando {names[0]}. {ranges[0]}.',
    },
    chartHeading: '{title}',
    chartContainerLabel: 'Gráfico interactivo {title}. Encienda el modo foco para navegar, presionando las teclas derecha e izquierda navega entre categorías, si no, utilizar las flechas arriba o abajo.',
    svgContainerTitle: '{chartTitle}',
    svgContainerLabel: ' ',
    chartTypes: {
      barMultiple: 'Gráfico de barras con {numSeries} series de datos.',
      barSingle:'Gráfico de barras con {numPoints} {#eq numPoints 1}serie{else}series{/eq}.',
      combinationChart:'Gráfico de combinación con {numSeries} series de datos.',
      columnMultiple: 'Gráfico de columnas con {numSeries} series de datos.',
      columnSingle: 'Gráfico de columnas con {numPoints} {#eq numPoints 1}barra{else}barras{/eq}.',
      defaultMultiple: 'Gráfico con {numSeries} series de datos.',
      defaultSingle: 'Gráfico con {numSeries} {#plural(numPoints, series, serie)} de datos.',
      emptyChart: 'Gráfico vacío',
      lineMultiple: 'Gráfico lineal con {numSeries} líneas.',
      lineSingle: 'Gráfico de lineas con {numPoints} {#plural(numPoints, serie, series)} de datos.',
      pieMultiple: 'Gráfico de pastel con {numSeries} partes.',
      pieSingle: 'Gráfico de pastel con {numPoints} {#plural(numPoints, partes, parte)}.',
      splineMultiple: 'Gráfico de líneas con {numSeries} líneas.',
      splineSingle: 'Gráfico de líneas con {numPoints} {#eq numPoints 1}serie{else}series{/eq} de datos.',
      unknownMap: 'Gráfico no especificado con {numSeries} series de datos.',
    },
    credits: '.',
    exporting: {
      chartMenuLabel: 'Exportación del gráfico',
      menuButtonLabel: 'Ver opciones de descarga',
      exportRegionLabel: 'Menú opciones de descarga',
    },
    navigationHint:
      'Use la tecla G para enfocar el gráfico {#plural(seriesNumber, y navegar entre series de datos,)}',
    defaultChartTitle: 'Categoría',
    longDescriptionHeading: '',
    noDescription: 'No disponible',
    structureHeading: 'Estructura',
        rangeSelector: {
      clickButtonAnnouncement: 'Viendo {axisRangeDescription}',
      dropdownLabel: '{rangeTitle}',
      maxInputLabel: 'Seleccione fecha final',
      minInputLabel: 'Seleccione fecha inicial.',
    },
    legend:{
      legendItem: 'Mostrar {itemName}',
      legendLabel: '{legendTitle}',
      legendLabelNoTitle: 'Filtrar datos {legendTitle}'
    },
    resetZoom: 'Reestablecer zoom',
    resetZoomTitle: 'Reestablecer zoom level 1:1',
    screenReaderSection: {
      endOfChartMarker:'Final del gráfico interactivo.',
    },
    series: {
      summary: {
        default: 'series {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
        defaultCombination: 'series {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
        bar: 'serie de barras {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}barra{else}barras{/eq}.',
        barCombination: 'series {seriesNumber} de {chart.series.length}. Serie de barras con {series.points.length} {#eq series.points.length 1}barra{else}barras{/eq}.',
        column: 'serie de barras {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}barra{else}barras{/eq}.',
        columnCombination: 'series {seriesNumber} de {chart.series.length}. Serie de barras con {series.points.length} {#eq series.points.length 1}barra{else}barras{/eq}.',
        line: 'línea {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
        lineCombination: 'series {seriesNumber} de {chart.series.length}. Línea con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
        pie: 'pastel {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}parte{else}partes{/eq}.',
        pieCombination: 'series {seriesNumber} de {chart.series.length}. Pastel con {series.points.length} {#eq series.points.length 1}parte{else}partes{/eq}.',
        spline: 'línea {seriesNumber} de {chart.series.length} con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
        splineCombination: 'series {seriesNumber} de {chart.series.length}. Línea con {series.points.length} {#eq series.points.length 1}serie{else}series{/eq} de datos.',
      },
      // description: '{description}',
      description: ' ',
      pointAnnotationsDescription: ' ',
      // pointAnnotationsDescription: '{#each annotations}Nota: {this}{/each}',
      xAxisDescription: 'Eje X, {name}',
      yAxisDescription: 'Eje Y, {name}',
    },
    

    table: {
      tableSummary: 'Tabla que representa al gráfico',
      viewAsDataTableButtonText: 'Ver como tabla de datos, {chartTitle}'
    },
    zoom:{
      mapZoomIn: 'Acercar el gráfico.',
      mapZoomOut: 'Alejar el gráfico.',
      resetZoomButton: 'Reiniciar vista.',
    }
  },
};
